# Generated by Django 3.0.7 on 2020-06-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=150)),
                ('division', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
