# Generated by Django 3.0.7 on 2020-06-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_auto_20200624_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(max_length=50),
        ),
    ]
