# Generated by Django 3.0.7 on 2020-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_auto_20200624_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
