# Generated by Django 3.0.7 on 2020-06-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
