# Generated by Django 3.0.7 on 2020-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20200620_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_images',
            field=models.FileField(default=2, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
